# Generated by Django 3.2.16 on 2022-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixhelpers', '0002_auto_20180320_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
