# Generated by Django 4.2.4 on 2023-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0004_auto_20211208_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedstripeobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="registeredapplepaydomain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
