# Generated by Django 4.1.9 on 2023-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0004_auto_20211208_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedstripeobject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredapplepaydomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
