codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 2%
        base: auto
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  require_changes: yes
  layout: "header, diff, files"
  behavior: default
  require_changes: no
