# SonarQube Properties
sonar.organization=ofejiroederhi
sonar.projectKey=ofejiroederhi_pretix
sonar.projectName=pretix
sonar.projectVersion=1.0

sonar.sources=src/pretix
sonar.tests=src/tests
sonar.inclusions=src/**/*.py
sonar.test.inclusions=src/tests/**/*.py

# Coverage Report and Python Version
sonar.python.version=3.11
sonar.python.coverage.reportPaths=src/coverage.xml

sonar.exclusions=src/pretix/locale/**,src/pretix/**/migrations/**,src/pretix/static/**,src/pretix/**/node_modules/**

sonar.sourceEncoding=UTF-8
