# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models

import pretix.base.models.vouchers


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0004_auto_20160209_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Redeemed'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=pretix.base.models.vouchers.generate_code, max_length=255, verbose_name='Voucher code'),
        ),
    ]
