# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0005_auto_20160211_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Tax rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderposition',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax value'),
            preserve_default=False,
        ),
    ]
