# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0007_auto_20160211_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('street', models.TextField(verbose_name='Address')),
                ('zipcode', models.CharField(max_length=30, verbose_name='ZIP code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone number')),
                ('vat_id', models.CharField(blank=True, max_length=255, verbose_name='VAT ID')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Order')),
            ],
        ),
    ]
