# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models

import pretix.base.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0009_auto_20160222_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='secret',
            field=models.CharField(default=pretix.base.models.orders.generate_position_secret, max_length=64),
        ),
    ]
