# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0010_orderposition_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_fee_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment method fee tax rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_fee_tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment method fee tax'),
        ),
    ]
