# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0012_auto_20160312_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
