# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0013_invoice_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_text',
            field=models.TextField(blank=True),
        ),
    ]
