# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 11:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0018_auto_20160326_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='option',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='pretixbase.QuestionOption'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pretixbase.Question'),
        ),
    ]
