# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 19:43
from __future__ import unicode_literals

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0019_auto_20160326_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=i18nfield.fields.I18nTextField(blank=True, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='answers', to='pretixbase.QuestionOption'),
        ),
    ]
