# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0028_auto_20160816_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no_charfield',
            field=models.CharField(db_index=True, default='', max_length=19),
            preserve_default=False,
        ),
    ]
