# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0029_invoice_no_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('event', 'invoice_no_charfield')]),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
    ]
