# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0030_auto_20160816_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_no_charfield',
            new_name='invoice_no',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('event', 'invoice_no')]),
        ),
    ]
