# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0031_auto_20160816_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allow_cancel',
            field=models.BooleanField(default=True, help_text='Whether this product might or not be cancelled.', verbose_name='Allow a product to be cancelled'),
        ),
    ]
