# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0033_auto_20160821_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='introductory_text',
            field=models.TextField(blank=True),
        ),
    ]
