# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0036_auto_20160902_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_provider_text',
            field=models.TextField(blank=True),
        ),
    ]
