# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0037_invoice_payment_provider_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpermission',
            name='can_view_vouchers',
            field=models.BooleanField(default=True, verbose_name='Can view vouchers'),
        ),
        migrations.AlterField(
            model_name='item',
            name='allow_cancel',
            field=models.BooleanField(default=True, help_text='If you deactivate this, an order including this product might not be canceled by the user. It may still be canceled by you.', verbose_name='Allow product to be canceled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'pending'), ('p', 'paid'), ('e', 'expired'), ('c', 'canceled'), ('r', 'refunded')], db_index=True, max_length=3, verbose_name='Status'),
        ),
    ]
