# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0045_auto_20161108_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta_info',
            field=models.TextField(blank=True, null=True, verbose_name='Meta information'),
        ),
    ]
