# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0054_auto_20170107_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerpermission',
            name='can_change_permissions',
            field=models.BooleanField(default=True, verbose_name='Can change permissions'),
        ),
    ]
