# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import pretix.base.models.organizer


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0055_organizerpermission_can_change_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerpermission',
            name='invite_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizerpermission',
            name='invite_token',
            field=models.CharField(blank=True, default=pretix.base.models.organizer.generate_invite_token, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organizerpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_perms', to=settings.AUTH_USER_MODEL),
        ),
    ]
