# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 21:16
from __future__ import unicode_literals

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0056_auto_20170414_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemaddon',
            options={'ordering': ('position', 'pk')},
        ),
        migrations.AddField(
            model_name='itemaddon',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='description',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='This is shown below the variation name in lists.', null=True, verbose_name='Description'),
        ),
    ]
