# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 10:27
from __future__ import unicode_literals

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0059_checkin_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_admission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admission time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=i18nfield.fields.I18nTextField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
