# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:31
from __future__ import unicode_literals

from django.db import migrations

import pretix.base.i18n


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0060_auto_20170113_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=pretix.base.i18n.I18nCharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
