# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 09:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import pretix.base.models.organizer


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0061_auto_20170521_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAPIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('active', models.BooleanField(default=True)),
                ('token', models.CharField(default=pretix.base.models.organizer.generate_api_token, max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='pretixbase.Team')),
            ],
        ),
    ]
