# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models

import pretix.base.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0063_auto_20170702_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pretix.base.models.orders.answerfile_name),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('N', 'Number'), ('S', 'Text (one line)'), ('T', 'Multiline text'), ('B', 'Yes/No'), ('C', 'Choose one from a list'), ('M', 'Choose multiple from a list'), ('F', 'File upload')], max_length=5, verbose_name='Question type'),
        ),
    ]
