# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0071_auto_20170729_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
