# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:17
from __future__ import unicode_literals

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0078_auto_20171003_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='api_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pretixbase.TeamAPIToken'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=200, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If you have many products, you can optionally sort them into categories to keep things organized.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pretixbase.ItemCategory', verbose_name='Category'),
        ),
    ]
