# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0078_auto_20171206_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('organizer', 'slug')]),
        ),
    ]
