# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0080_question_ask_during_checkin'),
        ('pretixbase', '0079_auto_20180117_1242'),
    ]

    operations = [
    ]
