# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


def clear_quota_caches(app, schema_editor):
    Quota = app.get_model('pretixbase', 'Quota')
    Quota.objects.all().update(cached_availability_time=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0080_auto_20171016_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='cached_availability_paid_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            clear_quota_caches, migrations.RunPython.noop
        )
    ]
