# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


def set_position(apps, schema_editor):
    Question = apps.get_model('pretixbase', 'Question')
    for q in Question.objects.all():
        for i, option in enumerate(q.options.all()):
            option.position = i
            option.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0082_auto_20180222_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            set_position, 
            reverse_code=migrations.RunPython.noop,
        ),
    ]
