# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0083_auto_20180228_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Danish'), ('de', 'German'), ('de-informal', 'German (informal)')], default='en', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Copenhagen', max_length=100, verbose_name='Timezone'),
        ),
    ]
