# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0081_merge_20180206_0954'),
        ('pretixbase', '0084_questionoption_position'),
    ]

    operations = [
    ]
