# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0085_merge_20180305_1149'),
        ('pretixbase', '0085_auto_20180312_1119'),
    ]

    operations = [
    ]
