# Generated by Django 2.1 on 2018-10-17 00:24

from django.db import migrations, models
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0099_auto_20180912_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartposition',
            old_name='attendee_name',
            new_name='attendee_name_cached',
        ),
        migrations.RenameField(
            model_name='orderposition',
            old_name='attendee_name',
            new_name='attendee_name_cached',
        ),
        migrations.AddField(
            model_name='cartposition',
            name='attendee_name_parts',
            field=jsonfallback.fields.FallbackJSONField(null=True, default={'migrated': True}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderposition',
            name='attendee_name_parts',
            field=jsonfallback.fields.FallbackJSONField(null=True, default={'migrated': True}),
            preserve_default=False,
        ),
    ]
