# Generated by Django 2.1.1 on 2018-11-14 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0102_auto_20181017_0024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderposition',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderposition',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderfee',
            name='fee_type',
            field=models.CharField(choices=[('payment', 'Payment fee'), ('shipping', 'Shipping fee'), ('service', 'Service fee'), ('cancellation', 'Cancellation fee'), ('other', 'Other fees'), ('giftcard', 'Gift card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_positions',
                                    to='pretixbase.Order', verbose_name='Order'),
        ),
    ]
