# Generated by Django 2.1 on 2019-02-14 10:41

import django.db.models.deletion
from django.db import migrations, models


def create_extension(apps, schema_editor):
    if 'postgresql' in schema_editor.connection.settings_dict['ENGINE']:
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")


def create_trigram_index(apps, schema_editor):
    if 'postgresql' in schema_editor.connection.settings_dict['ENGINE']:
        schema_editor.execute("CREATE INDEX pretixbase_ordersearchindex_s ON pretixbase_ordersearchindex USING gin (search_body gin_trgm_ops);")
        schema_editor.execute("CREATE INDEX pretixbase_ordersearchindex_spp ON pretixbase_ordersearchindex USING gin (payment_providers gin_trgm_ops);")


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0109_auto_20190208_1432'),
    ]

    operations = [
        migrations.RunPython(create_extension),
        migrations.CreateModel(
            name='OrderSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_body', models.TextField()),
                ('payment_providers', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ordersearchindex',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event'),
        ),
        migrations.AddField(
            model_name='ordersearchindex',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Order', unique=True),
        ),
        migrations.AddField(
            model_name='ordersearchindex',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Organizer'),
        ),
        migrations.RunPython(create_trigram_index)
    ]
