# Generated by Django 2.2 on 2019-09-18 15:38

from django.db import migrations
import pretix.base.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0135_auto_20190918_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlist',
            name='auto_checkin_sales_channels',
            field=pretix.base.models.fields.MultiStringField(default=[]),
        ),
    ]
