# Generated by Django 2.2.1 on 2019-09-18 15:37

import django.db.models.deletion
from django.db import migrations, models

import pretix.base.models.fields


def fwd(app, schema_editor):
    Team = app.get_model('pretixbase', 'Team')
    Team.objects.filter(can_change_organizer_settings=True).update(can_manage_gift_cards=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0135_auto_20190910_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_manage_gift_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            fwd, migrations.RunPython.noop
        ),
    ]
