# Generated by Django 2.2.1 on 2019-09-18 18:20

import django.db.models.deletion
from django.db import migrations, models

import pretix.base.models.fields
import pretix.base.models.giftcards


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0136_auto_20190918_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='secret',
            field=models.CharField(db_index=True, default=pretix.base.models.giftcards.gen_giftcard_secret, max_length=190),
        ),
        migrations.AlterUniqueTogether(
            name='giftcard',
            unique_together={('secret', 'issuer')},
        ),
    ]
