# Generated by Django 2.2.1 on 2019-09-18 19:10

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0137_auto_20190918_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='issue_giftcard',
            field=models.BooleanField(default=False),
        ),
    ]
