# Generated by Django 3.0.4 on 2020-04-18 09:54

import django_countries.fields
from django.db import migrations, models

import pretix.helpers.countries


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0150_auto_20200401_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='allow_multiple_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set(),
        ),
    ]
