# Generated by Django 3.0.6 on 2020-05-10 10:42

from django.db import migrations, models
import django_countries.fields
import pretix.helpers.countries


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0151_auto_20200421_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceaddress',
            name='country',
            field=django_countries.fields.CountryField(countries=pretix.helpers.countries.CachedCountries, max_length=2),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_guid',
            field=models.CharField(db_index=True, max_length=190),
        ),
    ]
