# Generated by Django 3.0.4 on 2020-04-18 10:17

import django_countries.fields
import jsonfallback.fields
from django.db import migrations

import pretix.helpers.countries


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0151_auto_20200418_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='rules',
            field=jsonfallback.fields.FallbackJSONField(default=dict),
        ),
    ]
