# Generated by Django 3.0.4 on 2020-04-19 12:09

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models

import pretix.helpers.countries


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0152_auto_20200418_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='pretixbase.Device'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='forced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='type',
            field=models.CharField(default='entry', max_length=100),
        ),
    ]
