# Generated by Django 3.0.4 on 2020-04-19 12:50

import django_countries.fields
from django.db import migrations, models

import pretix.helpers.countries


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0153_auto_20200419_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='allow_entry_after_exit',
            field=models.BooleanField(default=True),
        ),
    ]
