# Generated by Django 3.0.10 on 2020-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0164_subevent_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='recipient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
