# Generated by Django 3.0.11 on 2020-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0170_remove_hidden_urls'),
    ]
    replaces = [
        ('pretixbase', '0162b_auto_20201218_1810'),
        ('pretixbase', '0169b_auto_20201218_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfile',
            name='session_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cachedfile',
            name='web_download',
            field=models.BooleanField(default=True),
        ),
    ]
