# Generated by Django 3.0.11 on 2020-12-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0169_checkinlist_gates'),
        ('pretixbase', '0162b_auto_20201218_1810'),
    ]

    operations = [
    ]
