# Generated by Django 3.0.11 on 2020-11-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0170_remove_hidden_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_date_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_date_min',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_datetime_max',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_datetime_min',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_number_max',
            field=models.DecimalField(decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_number_min',
            field=models.DecimalField(decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='pretixbase.Item'),
        ),
    ]
