# Generated by Django 3.0.9 on 2020-12-02 12:37

from django.db import migrations
import pretix.base.models.fields
from pretix.base.channels import get_all_sales_channels


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0171_auto_20201126_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sales_channels',
            field=pretix.base.models.fields.MultiStringField(default=list(get_all_sales_channels().keys())),
        ),
    ]
