# Generated by Django 3.0.11 on 2020-12-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0173_auto_20201211_1648'),
        ('pretixbase', '0162b_auto_20201218_1810'),
    ]

    operations = [
    ]
