# Generated by Django 3.0.11 on 2021-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
