# Generated by Django 3.0.12 on 2021-03-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0177_auto_20210301_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='attendee_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='event_date_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pretixbase.Item'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pretixbase.ItemVariation'),
        ),
    ]
