# Generated by Django 3.0.10 on 2021-03-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0178_auto_20210308_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('orderposition', 'question'), ('cartposition', 'question')},
        ),
    ]
