# Generated by Django 3.0.13 on 2021-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0179_auto_20210311_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_checkin_orders',
            field=models.BooleanField(default=False),
        ),
    ]
