# Generated by Django 3.0.12 on 2021-03-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0179_auto_20210311_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('orderposition', 'question'), ('cartposition', 'question')},
        ),
        migrations.RemoveField(
            model_name='quota',
            name='cached_availability_number',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='cached_availability_paid_orders',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='cached_availability_state',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='cached_availability_time',
        ),
    ]
