# Generated by Django 3.0.12 on 2021-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0180_auto_20210324_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_checkin_orders',
            field=models.BooleanField(default=False),
        ),
    ]
