# Generated by Django 3.0.13 on 2021-04-06 14:31

from django.db import migrations, models


def set_can_manage_customers(apps, schema_editor):
    Team = apps.get_model('pretixbase', 'Team')
    Team.objects.filter(can_change_organizer_settings=True).update(can_manage_customers=True)
    Team.objects.filter(can_change_orders=True, all_events=True).update(can_manage_customers=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0182_auto_20210406_0725'),
    ]

    operations = [
        migrations.RunPython(
            set_can_manage_customers,
            migrations.RunPython.noop,
        ),
    ]
