# Generated by Django 3.0.13 on 2021-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0182_question_valid_file_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventitem',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subeventitem',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subeventitemvariation',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subeventitemvariation',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
