# Generated by Django 3.2.2 on 2021-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0185_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_to_organizer',
            field=models.BooleanField(null=True, default=False),
            preserve_default=False,
        ),
    ]
