# Generated by Django 3.2.2 on 2021-05-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0187_normalize_salutation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequiredAction',
        ),
    ]
