# Generated by Django 3.2.3 on 2021-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0189_auto_20210525_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='ignore_for_event_availability',
            field=models.BooleanField(default=False),
        ),
    ]
