# Generated by Django 3.2.3 on 2021-06-07 09:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0192_checkin_more_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checkin',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
    ]
