# Generated by Django 3.2.3 on 2021-06-11 13:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0192_checkin_more_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checkin',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='custom_followup_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
