# Generated by Django 3.2.3 on 2021-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0194_membership_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='fee_internal_type',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='fee_type',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
