# Generated by Django 3.2.4 on 2021-09-14 08:14

from django.db import migrations, models

import pretix.base.models.fields
import pretix.base.models.items


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0196_auto_20210523_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='hide_without_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='sales_channels',
            field=pretix.base.models.fields.MultiStringField(default=pretix.base.models.items._all_sales_channels_identifiers),
        ),
    ]
