# Generated by Django 3.2.4 on 2021-09-30 10:25
from datetime import datetime, timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0197_auto_20210914_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_to_customer',
            field=models.DateTimeField(blank=True, null=True, default=datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
    ]
