# Generated by Django 3.2.4 on 2021-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0200_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='event_location',
            field=models.TextField(null=True),
        ),
    ]
