# Generated by Django 3.2.9 on 2021-11-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0201_invoiceline_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
