# Generated by Django 3.2.2 on 2021-11-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0202_user_needs_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='is_bundled',
            field=models.BooleanField(default=False),
        ),
    ]
