# Generated by Django 3.2.9 on 2021-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0204_orderposition_backfill_is_bundled'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
    ]
