# Generated by Django 3.2.4 on 2022-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0206_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='internal_name',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='keep_gross_if_rate_changes',
            field=models.BooleanField(default=False),
        ),
    ]
