# Generated by Django 3.2.4 on 2022-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0207_auto_20220119_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_backend_identifier',
            field=models.CharField(db_index=True, max_length=190, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('auth_backend', 'auth_backend_identifier')},
        ),
    ]
