# Generated by Django 3.2.12 on 2022-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0209_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='external_identifier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
