# Generated by Django 3.2.12 on 2022-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0209_auto_20220303_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='condition_apply_to_addons',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='subevent_mode',
            field=models.CharField(default='mixed', max_length=50),
        ),
    ]
