# Generated by Django 3.2.12 on 2022-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0211_auto_20220314_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartposition',
            name='includes_tax',
        ),
        migrations.RemoveField(
            model_name='cartposition',
            name='override_tax_rate',
        ),
        migrations.RemoveField(
            model_name='cartposition',
            name='price_before_voucher',
        ),
        migrations.RemoveField(
            model_name='orderposition',
            name='price_before_voucher',
        ),
    ]
