# Generated by Django 3.2.2 on 2022-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0212_auto_20220318_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='condition_ignore_voucher_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
