# Generated by Django 3.2.12 on 2022-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0214_customer_notes_ext_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='force_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
