# Generated by Django 3.2.12 on 2022-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0214_customer_notes_ext_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identifier',
            field=models.CharField(db_index=True, max_length=190),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organizer', 'email'), ('organizer', 'identifier')},
        ),
    ]
