# Generated by Django 3.2.12 on 2022-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0215_customer_organizer_identifier_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='force_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
