# Generated by Django 3.2.12 on 2022-06-15 08:10

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0216_checkin_forced_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerFooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', i18nfield.fields.I18nCharField(max_length=200)),
                ('url', models.URLField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='pretixbase.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='EventFooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', i18nfield.fields.I18nCharField(max_length=200)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='pretixbase.event')),
            ],
        ),
    ]
