# Generated by Django 3.2.2 on 2022-06-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0217_eventfooterlink_organizerfooterlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='addon_match',
            field=models.BooleanField(default=False),
        ),
    ]
