# Generated by Django 3.2.4 on 2021-12-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0221_clean_nonunique_question_identifiers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('event', 'identifier')},
        ),
    ]
