# Generated by Django 3.2.2 on 2022-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0222_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_identifier',
            field=models.CharField(db_index=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(db_index=True, max_length=190, null=True),
        ),
    ]
