# Generated by Django 3.2.12 on 2022-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0222_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_usages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
