# Generated by Django 3.2.16 on 2022-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0224_eventmetaproperty_filter_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='process_initiated',
            field=models.BooleanField(null=True),
        ),
    ]
