# Generated by Django 3.2.16 on 2022-12-09 10:06

import django.db.models.deletion
from django.db import migrations, models

import pretix.base.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0225_orderpayment_process_initiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariationMetaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_values', to='pretixbase.itemmetaproperty')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_values', to='pretixbase.itemvariation')),
            ],
            options={
                'unique_together': {('variation', 'property')},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
