# Generated by Django 3.2.16 on 2023-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0227_item_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='checkin_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='valid_if_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='blocked',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
