# Generated by Django 3.2.17 on 2023-02-14 10:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0232_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='ignore_from_quota_while_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
