# Generated by Django 3.2.18 on 2023-03-16 20:23

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0234_total_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='cartposition',
            name='custom_price_input',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='cartposition',
            name='line_price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='cartposition',
            name='listed_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='cartposition',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='cartposition',
            name='price_after_voucher',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='condition_min_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='foreign_currency_rate',
            field=models.DecimalField(decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='gross_value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='designated_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderfee',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderfee',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='voucher_budget_use',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='subeventitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='subeventitemvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
