# Generated by Django 3.2.18 on 2023-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0236_reusable_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_string_length_max',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
