# Generated by Django 3.2.18 on 2023-05-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0237_question_valid_string_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='owner_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_gift_cards', to='pretixbase.orderposition'),
        ),
    ]
