# Generated by Django 3.2.18 on 2023-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0238_giftcard_owner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtransaction',
            name='info',
            field=models.JSONField(null=True),
        ),
    ]
