# Generated by Django 3.2.18 on 2023-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0238_giftcard_owner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmetaproperty',
            name='allowed_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itemmetaproperty',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
