# Generated by Django 3.2.18 on 2023-05-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0238_giftcard_owner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtransaction',
            name='acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='pretixbase.organizer'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='info',
            field=models.JSONField(null=True),
        ),
    ]
