# Generated by Django 3.2.18 on 2023-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0239_giftcard_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='all_addons_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='all_bundles_included',
            field=models.BooleanField(default=False),
        ),
    ]
