# Generated by Django 4.1.9 on 2023-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0242_auto_20230512_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='os_name',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
