# Generated by Django 4.2.4 on 2023-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0246_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinlist",
            name="consider_tickets_used",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="checkinlist",
            name="ignore_in_statistics",
            field=models.BooleanField(default=False),
        ),
    ]
