# Generated by Django 4.2.4 on 2023-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0247_checkinlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="free_price_suggestion",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name="itemvariation",
            name="free_price_suggestion",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
