# Generated by Django 4.2.4 on 2023-10-31 10:08
import i18nfield.fields
from django.db import migrations, models

import pretix.helpers.json


def convert_allowed_values(apps, schema_editor):
    EventMetaProperty = apps.get_model('pretixbase', 'EventMetaProperty')
    for emp in EventMetaProperty.objects.filter(allowed_values__isnull=False):
        emp.allowed_values_new = [
            {"key": _v.strip(), "label": {"en": _v.strip()}}
            for _v in emp.allowed_values.splitlines()
        ]
        emp.save(update_fields=["allowed_values_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0248_item_free_price_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmetaproperty",
            name="filter_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventmetaproperty",
            name="public_label",
            field=i18nfield.fields.I18nCharField(null=True),
        ),
        migrations.AddField(
            model_name="eventmetaproperty",
            name="allowed_values_new",
            field=models.JSONField(null=True, encoder=pretix.helpers.json.CustomJSONEncoder),
        ),
        migrations.RunPython(
            convert_allowed_values,
            migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="eventmetaproperty",
            name="allowed_values",
        ),
        migrations.RenameField(
            model_name="eventmetaproperty",
            new_name="allowed_values",
            old_name="allowed_values_new",
        ),
    ]
