# Generated by Django 4.2.4 on 2023-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0252_logentry_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="checkin_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="itemvariation",
            name="checkin_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="checkin_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="show_during_checkin",
            field=models.BooleanField(default=False),
        ),
    ]
