# Generated by Django 4.2.4 on 2023-11-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0254_alter_logentry_organizer_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="available_from_mode",
            field=models.CharField(default="hide", max_length=16),
        ),
        migrations.AddField(
            model_name="item",
            name="available_until_mode",
            field=models.CharField(default="hide", max_length=16),
        )
    ]
