# Generated by Django 4.2.9 on 2024-01-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0256_itemvariation_unavail_modes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="default_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
    ]
