# Generated by Django 4.2.8 on 2024-03-24 17:55

from django.db import migrations
from i18nfield.strings import LazyI18nString

from pretix.base.channels import get_all_sales_channel_types


def create_sales_channels(apps, schema_editor):
    channel_types = get_all_sales_channel_types()
    type_to_channel = dict()

    Organizer = apps.get_model('pretixbase', 'Organizer')
    for o in Organizer.objects.all():
        for t in channel_types.values():
            if not t.default_created:
                continue
            type_to_channel[t.identifier] = o.sales_channels.get_or_create(
                type=t.identifier,
                defaults=dict(
                    identifier=t.identifier,
                    label=LazyI18nString.from_gettext(t.verbose_name),
                ),
            )[0]
    full_set = set(type_to_channel.keys())

    for model in ("Discount", "Event", "Item", "ItemVariation"):
        M = apps.get_model('pretixbase', model)
        for d in M.objects.all():
            if set(d.sales_channels) != full_set:
                d.all_sales_channels = False
                d.save()
                for s in d.sales_channels:
                    d.limit_sales_channels.add(type_to_channel[s])

    CheckinList = apps.get_model('pretixbase', 'CheckinList')
    for c in CheckinList.objects.all():
        for s in c.auto_checkin_sales_channel_types:
            c.auto_checkin_sales_channels.add(type_to_channel[s])

    Order = apps.get_model('pretixbase', 'Order')
    for k, v in type_to_channel.items():
        Order.objects.filter(sales_channel_type=k, sales_channel__isnull=True).update(sales_channel=v)


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0258_saleschannel_and_more"),
    ]

    operations = [
        migrations.RunPython(create_sales_channels, migrations.RunPython.noop),
    ]
