# Generated by Django 4.2.10 on 2024-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0258_uniq_indx"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="require_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
