# Generated by Django 4.2.10 on 2024-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0258_uniq_indx"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="reusablemedium",
            index_together=set(),
        ),
    ]
