# Generated by Django 4.2.10 on 2024-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0261_userknownloginsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="subevent",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
