# Generated by Django 4.2.10 on 2024-04-09 07:32

from django.db import migrations


def change_currencies(apps, schema_editor):
    Event = apps.get_model("pretixbase", "Event")
    Event.objects.filter(
        currency__in={
            'XAG', 'XAU', 'XBA', 'XBB', 'XBC', 'XBD', 'XDR', 'XPD', 'XPT', 'XSU', 'XTS', 'XUA',
        }
    ).update(currency='XXX')



class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0262_subevent_comment"),
    ]

    operations = [
        migrations.RunPython(
            change_currencies, migrations.RunPython.noop
        )
    ]
