# Generated by Django 4.2.13 on 2024-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0268_remove_subevent_items_remove_subevent_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_meta_info',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
