# Generated by Django 4.2.11 on 2024-05-27 13:19

from django.db import migrations, models

import pretix.base.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0270_historicpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcategory",
            name="cross_selling_condition",
            field=models.CharField(null=True, max_length=10),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="cross_selling_mode",
            field=models.CharField(null=True, max_length=5),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="cross_selling_match_products",
            field=models.ManyToManyField(
                related_name="matched_by_cross_selling_categories", to="pretixbase.item"
            ),
        ),
    ]
