# Generated by Django 4.2.8 on 2024-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pretixbase",
            "0273_remove_checkinlist_auto_checkin_sales_channels",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="tax_code",
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name="orderfee",
            name="tax_code",
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name="orderposition",
            name="tax_code",
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name="taxrule",
            name="code",
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tax_code",
            field=models.CharField(max_length=190, null=True),
        ),
    ]
