# Generated by Django 4.2.17 on 2025-01-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0274_tax_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cart_id", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("testmode", models.BooleanField(default=False)),
                ("session_data", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="pretixbase.customer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.event",
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.saleschannel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoiceaddress",
            name="checkout_session",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_address",
                to="pretixbase.checkoutsession",
            ),
        ),
    ]
