# Generated by Django 4.2.17 on 2025-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0274_tax_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="valid_number_max",
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="valid_number_min",
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
    ]
