# Generated by Django 4.2.16 on 2025-02-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0276_item_hidden_if_item_available_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sync_provider", models.CharField(max_length=128)),
                ("triggered_by", models.CharField(max_length=128)),
                ("triggered", models.DateTimeField(auto_now_add=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_sync_jobs",
                        to="pretixbase.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "sync_provider")},
            },
        ),
    ]
