# Generated by Django 4.2.16 on 2025-03-04 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0278_ordersynclink"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersynclink",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
