# Generated by Django 4.2.19 on 2025-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0278_login_source_add_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='subevent_date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='subevent_date_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
