# Generated by Django 4.2.20 on 2025-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0279_discount_event_date_from_discount_event_date_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="locale",
            field=models.CharField(default="en", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(default="en", max_length=50),
        ),
    ]
