# Generated by Django 4.2.17 on 2025-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0279_discount_event_date_from_discount_event_date_until"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="sent_to_customer",
            new_name="transmission_date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_to_transmission_info",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transmission_info",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transmission_provider",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transmission_status",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.RunSQL(
            "UPDATE pretixbase_invoice SET transmission_status = 'completed' WHERE transmission_date IS NOT NULL",
        ),
        migrations.AddField(
            model_name="invoice",
            name="transmission_type",
            field=models.CharField(default="email", max_length=255),
        ),
        migrations.AddField(
            model_name="invoiceaddress",
            name="transmission_info",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="invoiceaddress",
            name="transmission_type",
            field=models.CharField(default="email", max_length=255),
        ),
    ]
