# Generated by Django 4.2.16 on 2025-04-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0279_discount_event_date_from_discount_event_date_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sync_provider", models.CharField(max_length=128)),
                ("triggered_by", models.CharField(max_length=128)),
                ("triggered", models.DateTimeField(auto_now_add=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_sync_jobs",
                        to="pretixbase.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "sync_provider")},
            },
        ),
        migrations.CreateModel(
            name="OrderSyncLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sync_provider", models.CharField(max_length=128)),
                ("external_object_type", models.CharField(max_length=128)),
                ("external_pk_name", models.CharField(max_length=128)),
                ("external_pk_value", models.CharField(max_length=128)),
                ("external_link_href", models.CharField(max_length=255, null=True)),
                (
                    "external_link_display_name",
                    models.CharField(max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_objects",
                        to="pretixbase.order",
                    ),
                ),
                (
                    "order_position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_objects",
                        to="pretixbase.orderposition",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["order", "sync_provider"],
                        name="pretixbase__order_i_23d278_idx",
                    )
                ],
            },
        ),
    ]
