# Generated by Django 4.2.16 on 2025-05-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0279_discount_event_date_from_discount_event_date_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
    ]
