# Generated by Django 4.2.20 on 2025-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0279_discount_event_date_from_discount_event_date_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='max_extend',
            field=models.DateTimeField(null=True),
        ),
    ]
