# Generated by Django 4.2.19 on 2025-05-19 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0279_discount_event_date_from_discount_event_date_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_gift_cards', to='pretixbase.customer'),
        ),
    ]
