# Generated by Django 4.2.23 on 2025-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0283_taxrule_default_taxrule_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedticketsecret',
            name='secret',
            field=models.BinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='secret',
            field=models.BinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name='revokedticketsecret',
            name='secret',
            field=models.BinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
