# Generated by Django 4.2.19 on 2025-08-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0284_ordersyncresult_ordersyncqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProgramTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_program_times',
                                   to='pretixbase.item')),
            ],
        ),
    ]
