# Generated by Django 4.2.16 on 2025-08-14 09:40

from django.db import migrations
from hierarkey.utils import CleanHierarkeyDuplicates


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0285_voucher_created"),
    ]

    operations = [
        CleanHierarkeyDuplicates("GlobalSettingsObject_SettingsStore"),
        CleanHierarkeyDuplicates("Organizer_SettingsStore"),
        CleanHierarkeyDuplicates("Event_SettingsStore"),
        migrations.AlterUniqueTogether(
            name="event_settingsstore",
            unique_together={("object", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="globalsettingsobject_settingsstore",
            unique_together={("key",)},
        ),
        migrations.AlterUniqueTogether(
            name="organizer_settingsstore",
            unique_together={("object", "key")},
        ),
    ]
