# Generated by Django 4.2.17 on 2025-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0286_settingsstore_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="plugins",
            field=models.TextField(default=""),
        ),
    ]
