# Generated by Django 4.2.23 on 2025-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0288_invoice_transmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_email",
            field=models.EmailField(max_length=190, null=True),
        ),
    ]
