# Generated by Django 4.2.17 on 2025-09-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0288_invoice_transmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="queued", max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sent", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(null=True)),
                ("error_detail", models.TextField(null=True)),
                ("subject", models.TextField()),
                ("body_plain", models.TextField()),
                ("body_html", models.TextField()),
                ("sender", models.CharField(max_length=500)),
                ("headers", models.JSONField(default=dict)),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(default=list)),
                ("bcc", models.JSONField(default=list)),
                ("should_attach_tickets", models.BooleanField(default=False)),
                ("should_attach_ical", models.BooleanField(default=False)),
                ("should_attach_other_files", models.JSONField(default=list)),
                ("actual_attachments", models.JSONField(default=list)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_mails",
                        to="pretixbase.customer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_mails",
                        to="pretixbase.event",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_mails",
                        to="pretixbase.order",
                    ),
                ),
                (
                    "orderposition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_mails",
                        to="pretixbase.orderposition",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_mails",
                        to="pretixbase.organizer",
                    ),
                ),
                (
                    "should_attach_cached_files",
                    models.ManyToManyField(
                        related_name="outgoing_mails", to="pretixbase.cachedfile"
                    ),
                ),
                (
                    "should_attach_invoices",
                    models.ManyToManyField(
                        related_name="outgoing_mails", to="pretixbase.invoice"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
