# Generated by Django 4.2.17 on 2025-09-08 08:14

from django.db import migrations


def set_default_cardtypes(apps, schema_editor):
    EventSettingsStore = apps.get_model("pretixbase", "Event_SettingsStore")
    ev_seen = set()
    insert_queue = []

    # Existing events that use pretix-zugferd and have explicitly disabled delivery dates
    for ev in EventSettingsStore.objects.filter(key="zugferd_include_delivery_date", value="False"):
        insert_queue.append(
            EventSettingsStore(
                object_id=ev.object_id,
                key="invoice_period",
                value="invoice_date",
            )
        )
        ev_seen.add(ev.object_id)

        if len(insert_queue) > 1000:
            EventSettingsStore.objects.bulk_create(insert_queue, ignore_conflicts=True)
            insert_queue.clear()

    # Existing events that previously hid their date on invoices
    # Ignore series as it doesn't make sense for them
    for ev in EventSettingsStore.objects.filter(key="show_dates_on_frontpage", value="False",
                                                object__has_subevents=False):
        if ev.object_id in ev_seen:
            continue

        insert_queue.append(
            EventSettingsStore(
                object_id=ev.object_id,
                key="invoice_period",
                value="auto_no_event",
            )
        )
        ev_seen.add(ev.object_id)

        if len(insert_queue) > 1000:
            EventSettingsStore.objects.bulk_create(insert_queue, ignore_conflicts=True)
            insert_queue.clear()

    EventSettingsStore.objects.bulk_create(insert_queue, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0288_invoice_transmission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceline",
            old_name="event_date_to",
            new_name="period_end",
        ),
        migrations.RenameField(
            model_name="invoiceline",
            old_name="event_date_from",
            new_name="period_start",
        ),
    ]
