# Generated by Django 4.2.17 on 2025-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0289_invoiceline_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="plugin_data",
            field=models.JSONField(default=dict),
        ),
    ]
