# Generated by Django 4.2.16 on 2025-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0290_invoice_plugin_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="object_id",
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
