# Generated by Django 4.2.17 on 2025-04-20 13:58

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0292_giftcard_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartposition",
            name="price_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="cartposition",
            name="tax_code",
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name="cartposition",
            name="tax_value_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="orderfee",
            name="tax_value_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="orderfee",
            name="value_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="orderposition",
            name="price_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="orderposition",
            name="tax_value_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tax_value_includes_rounding_correction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=13
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rounding_mode",
            field=models.CharField(default="line", max_length=100),
        ),
    ]
