# Generated by Django 4.2.23 on 2025-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0293_cartposition_price_includes_rounding_correction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
