# Generated by Django 4.2.19 on 2025-08-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0293_cartposition_price_includes_rounding_correction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProgramTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_times',
                                   to='pretixbase.item')),
            ],
        ),
    ]
