# Generated by Django 4.2.24 on 2025-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0295_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_from_state",
            field=models.CharField(max_length=190, null=True),
        ),
    ]
