# Generated by Django 4.2.27 on 2026-01-21 12:06

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0296_invoice_invoice_from_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemprogramtime",
            name="location",
            field=i18nfield.fields.I18nTextField(max_length=200, null=True),
        )
    ]
