# Generated by Django 4.2.28 on 2026-02-13 11:30

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    Question = apps.get_model('pretixbase', 'Question')
    for q in Question.objects.filter(valid_file_portrait=True):
        q.valid_file_ratio = "3:4"
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0297_outgoingmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_file_ratio',
            field=models.CharField(
                blank=True,
                choices=[('free', 'Free cropping'), ('3:4', 'Portrait (3:4)'), ('1:1', 'Square (1:1)'), ('4:3', 'Landscape (4:3)'), ('16:9', 'Widescreen (16:9)')],
                help_text='If loaded, the user will be asked to crop the image to this ratio.',
                max_length=16,
                null=True,
                verbose_name='Image Validation'
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='valid_file_portrait',
        ),
    ]
