# Generated by Django 4.2.27 on 2026-02-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0297_outgoingmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_provider', models.CharField(max_length=255)),
                ('payment_token', models.JSONField()),
                ('grace_warning_sent', models.BooleanField(default=False)),
                ('total_installments', models.PositiveIntegerField()),
                ('installments_paid', models.PositiveIntegerField(default=0)),
                ('amount_per_installment', models.DecimalField(decimal_places=2, max_digits=13)),
                ('status', models.CharField(default='active', max_length=20)),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plan', to='pretixbase.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='installment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='pretixbase.installmentplan'),
        ),
        migrations.CreateModel(
            name='ScheduledInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('due_date', models.DateTimeField()),
                ('state', models.CharField(db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='pretixbase.orderpayment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='pretixbase.installmentplan')),
            ],
            options={
                'ordering': ('installment_number',),
                'indexes': [models.Index(fields=['due_date', 'state'], name='pretixbase__due_dat_14c227_idx')],
                'unique_together': {('plan', 'installment_number')},
            },
        ),
    ]
