# Generated by Django 4.2.27 on 2026-01-21 12:06

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0298_pluggable_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemprogramtime",
            name="location",
            field=i18nfield.fields.I18nTextField(max_length=200, null=True),
        )
    ]
