# Generated by Django 4.2.28 on 2026-02-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_alter_customer_locale_alter_event_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='session_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='pretixbase.subeventsessionblock'),
        ),
    ]
