# Generated by Django 4.2.29 on 2026-03-19 14:24
import json
from collections import namedtuple
from itertools import chain, groupby

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields
from i18nfield.strings import LazyI18nString

import pretix.base.models.base
import pretix.base.models.fields


FakeQuestion = namedtuple(
    'FakeQuestion', 'id question position required'
)


def get_fake_questions(settings):
    def b(s):
        return s == 'True'
    fq = []
    sqo = json.loads(settings.get('system_question_order', '{}'))
    _ = LazyI18nString.from_gettext

    if b(settings.get('attendee_names_asked', 'True')):
        fq.append(FakeQuestion('attendee_name_parts', _('Attendee name'), sqo.get('attendee_name_parts', 0), b(settings.get('attendee_names_required'))))

    if b(settings.get('attendee_emails_asked')):
        fq.append(FakeQuestion('attendee_email', _('Attendee email'), sqo.get('attendee_email', 0), b(settings.get('attendee_emails_required'))))

    if b(settings.get('attendee_company_asked')):
        fq.append(FakeQuestion('company', _('Company'), sqo.get('company', 0), b(settings.get('attendee_company_required'))))

    if b(settings.get('attendee_addresses_asked')):
        fq.append(FakeQuestion('street', _('Street'), sqo.get('street', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('zipcode', _('ZIP code'), sqo.get('zipcode', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('city', _('City'), sqo.get('city', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('country', _('Country'), sqo.get('country', 0), b(settings.get('attendee_addresses_required'))))
    return fq


def migrate_questions_forward(apps, schema_editor):
    Event = apps.get_model("pretixbase", "Event")
    Item = apps.get_model("pretixbase", "Item")
    Question = apps.get_model("pretixbase", "Question")
    Questionnaire = apps.get_model("pretixbase", "Questionnaire")
    QuestionnaireChild = apps.get_model("pretixbase", "QuestionnaireChild")
    EventSettingsStore = apps.get_model('pretixbase', 'Event_SettingsStore')

    for event in Event.objects.iterator():
        # get relevant settings
        settings = {
            setting.key: setting.value for setting in EventSettingsStore.objects.filter(object_id=event.id, key__in=(
                'system_question_order', 'attendee_names_asked', 'attendee_names_required', 'attendee_emails_asked', 'attendee_emails_required',
                'attendee_company_asked', 'attendee_company_required', 'attendee_addresses_asked', 'attendee_addresses_required',
            ))
        }

        # get all questions (user-defined and system provided), along with the products for which they're asked
        questions = event.questions.all()
        children = sorted(chain((
            (item, q.position, q.id, q)
            for q in questions
            for item in q.items.values_list('id', 'internal_name', 'name')
        ), (
            (item, q.position, None, q)
            for q in get_fake_questions(settings)
            for item in event.items.filter(personalized=True).values_list('id', 'internal_name', 'name')
        )), key=lambda t: (t[0], t[1], t[2]))

        # group by item, creating a unique questionnaire per item
        item_questionnaires = (([t[3] for t in children], item_id) for item_id, children in groupby(children, key=lambda t: t[0]))

        # group again, merging all questionnaires with identical children
        merged_questionnaires = groupby(sorted(item_questionnaires, key=lambda t: [q.id for q in t[0]]), key=lambda t: t[0])
        for children, iterator in merged_questionnaires:
            items = [item for _c, item in iterator]

            # create questionnaires and children
            questionnaire = Questionnaire.objects.create(
                event=event, type='PS', position=0, all_sales_channels=True,
                internal_name=', '.join(str(iname or name) for (id, iname, name) in items)
            )
            questionnaire.items.set([id for (id, iname, name) in items])
            deps = {}
            for position, child in enumerate(children):
                if isinstance(child, FakeQuestion):
                    QuestionnaireChild.objects.create(
                        questionnaire=questionnaire,
                        position=position + 1,
                        system_question=child.id,
                        required=child.required,
                        label=child.question,
                    )
                else:
                    deps[child.id] = QuestionnaireChild.objects.create(
                        questionnaire=questionnaire,
                        position=position + 1,
                        user_question=child,
                        required=child.required,
                        label=child.question,
                        help_text=child.help_text,
                        dependency_question=deps[child.dependency_question.id] if child.dependency_question else None,
                        dependency_values=child.dependency_values,
                    )


def migrate_questions_backward(apps, schema_editor):
    pass  # as long as we don't delete the old columns, this is a no op. after that, it gets complicated...


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_pluggable_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('internal_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('all_sales_channels', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='pretixbase.event')),
                ('items', models.ManyToManyField(related_name='questionnaires', to='pretixbase.item')),
                ('limit_sales_channels', models.ManyToManyField(to='pretixbase.saleschannel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='QuestionnaireChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('system_question', models.CharField(max_length=25, null=True)),
                ('required', models.BooleanField(default=False)),
                ('label', i18nfield.fields.I18nTextField()),
                ('help_text', i18nfield.fields.I18nTextField(null=True)),
                ('dependency_values', pretix.base.models.fields.MultiStringField(default=[])),
                ('dependency_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='pretixbase.questionnairechild')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pretixbase.questionnaire')),
                ('user_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pretixbase.question')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.RunPython(
            migrate_questions_forward,
            migrate_questions_backward,
        ),
        # TODO remove old columns from Question model
    ]
