# Generated by Django 5.2.12 on 2026-04-15 20:10

from decimal import Decimal

from django.db import migrations, models

import pretix.helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_pluggable_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartposition',
            name='tax_rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='orderfee',
            name='tax_rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='tax_rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='rate',
            field=pretix.helpers.models.NormalizedDecimalField(decimal_places=4, max_digits=7),
        ),

    ]
