# Generated by Django 5.2.12 on 2026-04-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0299_fixup_eventmetaproperties"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventmetaproperty",
            unique_together={("organizer", "name")},
        ),
    ]
