# Generated by Django 5.2.12 on 2026-05-22 12:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models

from pretix.helpers.migration_utils import PostgreSQLAndStateOnly


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0299_itemprogramtime_location"),
    ]

    operations = [
        PostgreSQLAndStateOnly(
            UnaccentExtension(),
            migrations.RunSQL(
                sql="""
                CREATE TEXT SEARCH CONFIGURATION pretix_search( COPY = english );
                ALTER TEXT SEARCH CONFIGURATION pretix_search
                ALTER MAPPING FOR hword, hword_part, word
                WITH unaccent, english_stem;
                """,
                reverse_sql="""
                DROP TEXT SEARCH CONFIGURATION pretix_search;
                """
            ),
            migrations.CreateModel(
                name="OrderSearchIndex",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True, primary_key=True, serialize=False
                        ),
                    ),
                    ("last_modified", models.DateTimeField(auto_now=True)),
                    ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                    (
                        "organizer",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="pretixbase.organizer",
                        ),
                    ),
                    (
                        "event",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="pretixbase.event",
                        ),
                    ),
                    (
                        "order",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="pretixbase.order",
                        ),
                    ),
                    (
                        "orderpayment",
                        models.OneToOneField(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="search_index",
                            to="pretixbase.orderpayment",
                        ),
                    ),
                    (
                        "orderposition",
                        models.OneToOneField(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="search_index",
                            to="pretixbase.orderposition",
                        ),
                    ),
                    (
                        "orderrefund",
                        models.OneToOneField(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="search_index",
                            to="pretixbase.orderrefund",
                        ),
                    ),
                    (
                        "invoiceaddress",
                        models.OneToOneField(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="search_index",
                            to="pretixbase.invoiceaddress",
                        ),
                    ),
                    (
                        "invoice",
                        models.OneToOneField(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="search_index",
                            to="pretixbase.invoice",
                        ),
                    ),
                ],
                options={
                    "indexes": [
                        django.contrib.postgres.indexes.GinIndex(
                            models.F("search_vector"), name="ordersearchindex_vector"
                        )
                    ],
                    "constraints": [
                        models.UniqueConstraint(
                            condition=models.Q(
                                ("orderpayment__isnull", True),
                                ("orderposition__isnull", True),
                                ("orderrefund__isnull", True),
                                ("invoiceaddress__isnull", True),
                                ("invoice__isnull", True),
                            ),
                            fields=("order",),
                            name="ordersearchindex_one_per_order",
                        ),
                    ],
                },
            ),
        ),
    ]
