# Generated by Django 4.2.8 on 2024-07-01 09:27
import logging

from django.db import migrations
from django.db.models import Count

logger = logging.getLogger(__name__)


def clean_duplicate_secrets(apps, schema_editor):
    # This will autofix all possible duplicate Order.code and OrderPosition.secret values,
    # unless Order.code is already too long to append something. This would need to be fixed by
    # sysadmins manually.
    OrderPosition = apps.get_model("pretixbase", "OrderPosition")
    Order = apps.get_model("pretixbase", "Order")

    qs = OrderPosition.all.values("secret", "order__event__organizer_id").order_by().annotate(c=Count("*")).filter(c__gt=1)
    for row in qs:
        affected = OrderPosition.all.filter(
            **{k: v for k, v in row.items() if k != "c"}
        ).order_by("pk")
        logger.error(f"Found {row['c']} tickets with with the same secret \"{row['secret']}\" in organizer {row['order__event__organizer_id']}, all except one will be changed")
        for i, a in enumerate(affected):
            if i > 0:
                a.secret = a.secret + "__dupl__" + str(a.pk)
                logger.info(
                    f"Ticket {a.pk} has new secret {a.secret}"
                )
            a.save(update_fields=["organizer_id", "secret"])

    qs = Order.objects.values("code", "event__organizer_id").order_by().annotate(c=Count("*")).filter(c__gt=1)
    for row in qs:
        affected = Order.objects.filter(
            **{k: v for k, v in row.items() if k != "c"}
        ).order_by("pk")
        logger.error(f"Found {row['c']} orders with with the same code \"{row['code']}\" in organizer {row['event__organizer_id']}, all except one will be changed")
        for i, a in enumerate(affected):
            if i > 0:
                if len(a.code) > 16 - len(str(a.pk)):
                    raise ValueError(f"Cannot auto-fix order with duplicate code {a.code}, order code is too long already")
                a.code = a.code + str(a.pk).zfill(16 - len(a.code))
                logger.info(
                    f"Order {a.pk} has new code {a.code}"
                )
            a.save(update_fields=["organizer_id", "code"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "pretixbase",
            "0301_reusablemedium_remove_orderposition",
        ),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_secrets, migrations.RunPython.noop),
    ]
