# Generated by Django 5.2.12 on 2026-07-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0301_reusablemedium_remove_orderposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerssoprovider",
            name="allow_convert_to_sso",
            field=models.BooleanField(default=False),
        ),
    ]
