# Generated by Django 4.2.8 on 2024-07-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pretixbase",
            "0302_resolve_duplicate_codes_and_secrets",
        ),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE pretixbase_order "
            "SET organizer_id = (SELECT e.organizer_id FROM pretixbase_event e WHERE e.id = pretixbase_order.event_id) "
            "WHERE pretixbase_order.organizer_id IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE pretixbase_orderposition "
            "SET organizer_id = (SELECT e.organizer_id FROM pretixbase_order o LEFT JOIN pretixbase_event e ON e.id = o.event_id WHERE o.id = pretixbase_orderposition.order_id) "
            "WHERE pretixbase_orderposition.organizer_id IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="order",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pretixbase.organizer",
            ),
        ),
        migrations.AlterField(
            model_name="orderposition",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_positions",
                to="pretixbase.organizer",
            ),
        ),
    ]
