# Generated by Django 5.2.16 on 2026-08-05 08:00

import django.db.models.deletion
from django.db import migrations, models

import pretix.helpers.database


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0306_alter_eventmetaproperty_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLastSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.device",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="devicelastseen",
            index=pretix.helpers.database.BrinIndexIgnoredOnSQLite(
                models.F("last_seen"),
                autosummarize=True,
                name="pretixbase_device_last_seen",
            ),
        ),
    ]
