# Generated by Django 5.2.15 on 2026-08-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0308_checkoutsession_invoiceaddress_checkout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='container_type',
            field=models.CharField(default='P', max_length=5),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='checkoutsession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretixbase.checkoutsession'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretixbase.order'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('cartposition', 'question'), ('checkoutsession', 'question'), ('order', 'question'), ('orderposition', 'question')},
        ),
    ]
