# Generated by Django 5.2.12 on 2026-08-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0309_alter_questionanswer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="valid_string_length_min",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
