# Generated by Django 5.2.15 on 2026-08-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0309_questionnaire_questionnairechild'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='checkoutsession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretixbase.checkoutsession'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretixbase.order'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('cartposition', 'question'), ('checkoutsession', 'question'), ('order', 'question'), ('orderposition', 'question')},
        ),
    ]
