# Generated by Django 5.2.17 on 2026-09-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0310_question_valid_string_length_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="require_membership",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="require_membership_types",
            field=models.ManyToManyField(to="pretixbase.membershiptype"),
        ),
    ]
