# Generated by Django 5.2.17 on 2026-09-21 11:30

import django.db.models.deletion
from django.db import migrations, models


def fix_unshredded_invoices(apps, _):
    Invoice = apps.get_model("pretixbase", "Invoice")
    InvoiceLine = apps.get_model("pretixbase", "InvoiceLine")
    ignore_fields = (
        # bool/int fields are not listed and skipped automatically
        'prefix', 'invoice_no', 'full_invoice_no', 'invoice_from', 'invoice_from_name', 'invoice_from_zipcode',
        'invoice_from_city', 'invoice_from_state', 'invoice_from_country', 'invoice_from_tax_id',
        'invoice_from_vat_id', 'locale', 'payment_provider_stamp', 'footer_text', 'foreign_currency_display',
        'foreign_currency_source', 'transmission_type', 'transmission_provider', 'transmission_status',
    )

    for i in Invoice.objects.filter(shredded=True):
        for f in Invoice._meta.fields:
            if f.name in ignore_fields:
                continue
            val = getattr(i, f.name, None)
            if val and isinstance(val, str):
                setattr(i, f.name, "█")
            elif val and isinstance(val, list):  # jsonfield
                setattr(i, f.name, [])
            elif val and isinstance(val, dict):  # jsonfield
                setattr(i, f.name, {"_shredded": True})
        i.save()

    InvoiceLine.objects.filter(
        attendee_name__isnull=False,
        invoice__shredded=True
    ).update(attendee_name="█")



class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0310_question_valid_string_length_min"),
    ]

    operations = [
        migrations.RunPython(
            fix_unshredded_invoices,
            migrations.RunPython.noop,
        ),
    ]
