# Generated by Django 4.2.29 on 2026-03-19 14:24
import json
from collections import namedtuple
from itertools import chain, groupby

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models
from i18nfield.strings import LazyI18nString

import pretix.base.models.base
import pretix.base.models.fields
from pretix.base.i18n import language

FakeQuestion = namedtuple(
    'FakeQuestion', 'id question position required'
)


def get_fake_questions(settings):
    def b(s):
        return s == 'True'
    fq = []
    sqo = json.loads(settings.get('system_question_order', '{}'))
    _ = LazyI18nString.from_gettext

    if b(settings.get('attendee_names_asked', 'True')):
        fq.append(FakeQuestion('attendee_name_parts', _('Attendee name'), sqo.get('attendee_name_parts', 0), b(settings.get('attendee_names_required'))))

    if b(settings.get('attendee_emails_asked')):
        fq.append(FakeQuestion('attendee_email', _('Attendee email'), sqo.get('attendee_email', 0), b(settings.get('attendee_emails_required'))))

    if b(settings.get('attendee_company_asked')):
        fq.append(FakeQuestion('company', _('Company'), sqo.get('company', 0), b(settings.get('attendee_company_required'))))

    if b(settings.get('attendee_addresses_asked')):
        fq.append(FakeQuestion('street', _('Street'), sqo.get('street', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('zipcode', _('ZIP code'), sqo.get('zipcode', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('city', _('City'), sqo.get('city', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('state', _('State'), sqo.get('country', 0), b(settings.get('attendee_addresses_required'))))
        fq.append(FakeQuestion('country', _('Country'), sqo.get('country', 0), b(settings.get('attendee_addresses_required'))))
    return fq


def migrate_questions_forward(apps, schema_editor):
    from django.utils.translation import (
        get_supported_language_variant, gettext as _,
    )

    Event = apps.get_model("pretixbase", "Event")
    Item = apps.get_model("pretixbase", "Item")
    Question = apps.get_model("pretixbase", "Question")
    Questionnaire = apps.get_model("pretixbase", "Questionnaire")
    QuestionnaireChild = apps.get_model("pretixbase", "QuestionnaireChild")
    EventSettingsStore = apps.get_model('pretixbase', 'Event_SettingsStore')

    def create_grouped_item_questionnaires(event, children, label_prefix, questionnaire_type, personalized_items=None):
        # group by item, creating a unique questionnaire per item
        item_questionnaires = (([t[3] for t in children], item_id) for item_id, children in
                               groupby(children, key=lambda t: t[0]))

        # group again, merging all questionnaires with identical children
        merged_questionnaires = groupby(sorted(item_questionnaires, key=lambda t: [q.id for q in t[0]]),
                                        key=lambda t: t[0])
        for children, iterator in merged_questionnaires:
            items = [item for _c, item in iterator]

            internal_name = label_prefix + ', '.join(str(iname or name) for (id, iname, name) in items)
            if all(i.personalized for i in items) and len(items) == len(personalized_items) and questionnaire_type == 'PS':
                # if we have a questionnaire for exactly all personalized items, we just call it "Attendee data"
                # (same as the default questionnaire for new events)
                internal_name = _('Attendee data')

            # create questionnaires and children
            questionnaire = Questionnaire.objects.create(
                event=event, type=questionnaire_type, position=0, all_sales_channels=True,
                internal_name=internal_name
            )
            questionnaire.items.set([id for (id, iname, name) in items])
            deps = {}
            for position, child in enumerate(children):
                if isinstance(child, FakeQuestion):
                    QuestionnaireChild.objects.create(
                        questionnaire=questionnaire,
                        position=position + 1,
                        system_datafield=child.id,
                        required=child.required,
                        label=child.question,
                    )
                else:
                    deps[child.id] = QuestionnaireChild.objects.create(
                        questionnaire=questionnaire,
                        position=position + 1,
                        user_datafield=child,
                        required=child.required,
                        label=child.question,
                        help_text=child.help_text,
                        dependency_question=deps[child.dependency_question.id] if child.dependency_question else None,
                        dependency_values=child.dependency_values,
                    )

    for event in Event.objects.iterator():
        # get relevant settings
        settings = {
            setting.key: setting.value for setting in EventSettingsStore.objects.filter(object_id=event.id, key__in=(
                'system_question_order', 'attendee_names_asked', 'attendee_names_required', 'attendee_emails_asked', 'attendee_emails_required',
                'attendee_company_asked', 'attendee_company_required', 'attendee_addresses_asked', 'attendee_addresses_required', 'locale',
            ))
        }
        with language(get_supported_language_variant(settings.get('locale', 'en'))):
            # [P] get all ticket-level questions (user-defined and system provided), along with the products for which they're asked
            questions = event.questions.filter(container_type='P')

            # [PS] presale
            personalized_items = event.items.filter(personalized=True).values_list('id', 'internal_name', 'name')
            children = sorted(chain((
                (item, q.position, 0, q)
                for q in get_fake_questions(settings)
                for item in personalized_items
            ), (
                (item, q.position, q.id, q)
                for q in questions.filter(hidden=False, ask_during_checkin=False)
                for item in q.items.values_list('id', 'internal_name', 'name')
            )), key=lambda t: (t[0], t[1]))

            create_grouped_item_questionnaires(event, children, '', 'PS', personalized_items)

            # [PC] checkin
            children = sorted(chain((
                (item, q.position, q.id, q)
                for q in questions.filter(ask_during_checkin=True)
                for item in q.items.values_list('id', 'internal_name', 'name')
            )), key=lambda t: (t[0], t[1]))

            create_grouped_item_questionnaires(event, children, _('Check-in questions for '), 'PC')

            # [PH] hidden
            children = sorted(chain((
                (item, q.position, q.id, q)
                for q in questions.filter(hidden=True, ask_during_checkin=False)
                for item in q.items.values_list('id', 'internal_name', 'name')
            )), key=lambda t: (t[0], t[1]))

            create_grouped_item_questionnaires(event, children, _('Hidden questions for '), 'PH')

            # [O] get all order-level questions
            questions = list(event.questions.filter(container_type='O', hidden=False).order_by('position'))
            if questions:
                # create questionnaires and children
                questionnaire = Questionnaire.objects.create(
                    event=event, type='OS', position=0, all_sales_channels=True,
                    internal_name=_('Per-order questions'),
                )
                deps = {}
                for position, child in enumerate(questions):
                    deps[child.id] = QuestionnaireChild.objects.create(
                        questionnaire=questionnaire,
                        position=position + 1,
                        user_datafield=child,
                        required=child.required,
                        label=child.question,
                        help_text=child.help_text,
                        dependency_question=deps[child.dependency_question.id] if child.dependency_question else None,
                        dependency_values=child.dependency_values,
                    )


def migrate_questions_backward(apps, schema_editor):
    pass  # as long as we don't delete the old columns, this is a no op. after that, it gets complicated...


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0310_question_valid_string_length_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('internal_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('all_sales_channels', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='pretixbase.event')),
                ('items', models.ManyToManyField(related_name='questionnaires', to='pretixbase.item')),
                ('limit_sales_channels', models.ManyToManyField(to='pretixbase.saleschannel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='QuestionnaireChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('system_datafield', models.CharField(max_length=25, null=True)),
                ('required', models.BooleanField(default=False)),
                ('label', i18nfield.fields.I18nTextField()),
                ('help_text', i18nfield.fields.I18nTextField(null=True)),
                ('dependency_values', pretix.base.models.fields.MultiStringField(default=[])),
                ('dependency_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='pretixbase.questionnairechild')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pretixbase.questionnaire')),
                ('user_datafield', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pretixbase.question')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.RunPython(
            migrate_questions_forward,
            migrate_questions_backward,
        ),
        # TODO(questionnaires) remove old columns from Question model
    ]
