# Generated by Django 5.2.17 on 2026-09-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0310_question_valid_string_length_min"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ReferencedPayPalObject",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "reference",
                            models.CharField(db_index=True, max_length=190, unique=True),
                        ),
                        (
                            "order",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="pretixbase.order",
                            ),
                        ),
                        (
                            "payment",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="pretixbase.orderpayment",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "paypal_referencedpaypalobject",
                    },
                ),
            ],
            database_operations=[]
        )
    ]
