# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0002_auto_20151213_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDomain',
            fields=[
                ('domainname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='pretixbase.Organizer')),
            ],
            options={
                'verbose_name_plural': 'Known domains',
                'verbose_name': 'Known domain',
            },
        ),
    ]
