# Generated by Django 5.2.17 on 2026-09-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paypal", "0004_bigint"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ReferencedPayPalObject",
                ),
            ],
            database_operations=[]
        )
    ]
