# Generated by Django 3.0.9 on 2020-09-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0162_remove_seat_name'),
        ('banktransfer', '0006_auto_20200901_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('testmode', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=9)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banktransfer_refund_exports', to='pretixbase.Event')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banktransfer_refund_exports', to='pretixbase.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransferRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banktransfer.RefundExport')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Order')),
                ('refund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.OrderRefund')),
            ],
        ),
    ]
