# Generated by Django 3.0.9 on 2020-09-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer', '0007_banktransferrefund_refundexport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundexport',
            name='currency',
        ),
    ]
