# Generated by Django 3.2.18 on 2023-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer', '0007_refundexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
