# Generated by Django 4.2.4 on 2023-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banktransfer", "0009_banktransaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankimportjob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="refundexport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
