# Generated by Django 3.2.18 on 2023-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer', '0009_banktransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundexport',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
