# Generated by Django 4.2.9 on 2024-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banktransfer", "0010_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="external_id",
            field=models.CharField(db_index=True, max_length=190, null=True),
        ),
    ]
