#
# This file is part of pretix (Community Edition).
#
# Copyright (C) 2014-2020 Raphael Michel and contributors
# Copyright (C) 2020-2021 rami.io GmbH and contributors
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
# Public License as published by the Free Software Foundation in version 3 of the License.
#
# ADDITIONAL TERMS APPLY: Pursuant to Section 7 of the GNU Affero General Public License, additional terms are
# applicable granting you additional permissions and placing additional restrictions on your usage of this software.
# Please refer to the pretix LICENSE file to obtain the full terms applicable to this work. If you did not receive
# this file, see <https://pretix.eu/about/en/license>.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
from django.utils.translation import gettext_lazy as _
from reportlab.lib import pagesizes
from reportlab.lib.units import mm

TEMPLATES = {
    "a6land": {
        "label": _("A6 landscape"),
        "pagesize": pagesizes.landscape(pagesizes.A6),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "13.09",
                "bottom": "49.73",
                "fontsize": "23.6",
                "lineheight": 1,
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "121.83",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            }
        ],
    },
    "82x203butterfly": {
        "label": _("82 x 203 mm butterfly badge"),
        "pagesize": (82 * mm, 203 * mm),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "152.55",
                "fontsize": "20.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "72.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "144.55",
                "fontsize": "18.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "72.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "77.10",
                "bottom": "34.68",
                "fontsize": "20.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "72.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 180,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "77.06",
                "bottom": "44.28",
                "fontsize": "18.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "72.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 180,
                "align": "center",
            },
        ],
    },
    "83x50": {
        "label": _("83 x 50 mm label"),
        "pagesize": (83 * mm, 50 * mm),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "25.55",
                "fontsize": "16.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "73.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "18.55",
                "fontsize": "14.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "73.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
        ],
    },
    "75x52": {
        "label": _("75 x 52 mm label"),
        "pagesize": (75 * mm, 52 * mm),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "26.55",
                "fontsize": "16.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "65.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "19.55",
                "fontsize": "14.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "65.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
        ],
    },
    "70x36": {
        "label": _("70 x 36 mm label"),
        "pagesize": (70 * mm, 36 * mm),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "18.55",
                "fontsize": "16.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "60.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "11.55",
                "fontsize": "14.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "60.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
        ],
    },
    "100x50": {
        "label": _("100 x 50 mm label"),
        "pagesize": (100 * mm, 50 * mm),
        "layout": [
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "25.55",
                "fontsize": "20.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": True,
                "italic": False,
                "width": "90.00",
                "downward": False,
                "content": "attendee_name",
                "text": "John Doe",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
            {
                "type": "textarea",
                "page": 1,
                "locale": "",
                "left": "5.00",
                "bottom": "17.55",
                "fontsize": "18.0",
                "lineheight": "1",
                "color": [0, 0, 0, 1],
                "fontfamily": "Open Sans",
                "bold": False,
                "italic": False,
                "width": "90.00",
                "downward": False,
                "content": "attendee_company",
                "text": "Sample company",
                "text_i18n": {},
                "rotation": 0,
                "align": "center",
            },
        ],
    },
}
