name: Bug report
description: Please only create issues for bug reports. Feature requests or general questions should start as a "Discussion" on GitHub.
body:
  - type: markdown
    attributes:
      value: Please make sure to search our issues for similar bugs first! If bug has been reported already, react with a thumbs-up, and/or leave a comment providing further details.
  - type: textarea
    id: current
    attributes:
      label: Problem and impact
      description: What problem you're running into? What impact does it have on you / your event?
      placeholder: When trying to do ____, pretix suddenly shows me an error saying "...".
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Sometimes bugs are subtle and the expected behaviour may need some explanation. Leave empty if it's just "Don't be broken."
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: "Please give as much context as possible: Are there any settings that impact this behaviour?"
      placeholder: |
        1.
        2.
        3.
        4.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, show screenshots of the problem.
  - type: input
    id: link
    attributes:
      label: Link
      description: Link to the page where the bug occurs
  - type: input
    id: browser
    attributes:
      label: Browser (software, desktop or mobile?) and version
      description: Leave empty for backend problems
  - type: input
    id: os
    attributes:
      label: Operating system, dependency versions
      description: Leave empty for frontend problems
  - type: input
    id: version
    attributes:
      label: Version
      description: The pretix version in use. (Leave empty if unknown.)

