# Generated by Django 4.2.14 on 2024-07-24 08:36

import django.db.models.deletion
from django.db import migrations, models

import pretix.base.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0269_order_api_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoCheckinRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("mode", models.CharField(default="placed", max_length=100)),
                ("all_sales_channels", models.BooleanField(default=True)),
                ("all_products", models.BooleanField(default=True)),
                ("all_payment_methods", models.BooleanField(default=True)),
                (
                    "limit_payment_methods",
                    pretix.base.models.fields.MultiStringField(null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.event",
                    ),
                ),
                ("limit_products", models.ManyToManyField(to="pretixbase.item")),
                (
                    "limit_sales_channels",
                    models.ManyToManyField(to="pretixbase.saleschannel"),
                ),
                (
                    "limit_variations",
                    models.ManyToManyField(to="pretixbase.itemvariation"),
                ),
                (
                    "list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.checkinlist",
                    ),
                ),
            ],
        ),
    ]
