# Generated by Django 3.2.3 on 2021-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
