# Generated by Django 3.2.19 on 2023-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0003_rule_attach_ical'),  # todo: fix dependency after rebase
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='checked_in_status',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
