# Generated by Django 4.2.4 on 2023-09-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretixbase", "0246_bigint"),
        ("sendmail", "0006_rule_subevent_alter_rule_checked_in_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="subevent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pretixbase.subevent",
            ),
        ),
    ]
