# Generated by Django 4.2.28 on 2026-03-17 16:29

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0297_outgoingmail"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                ("platform", models.CharField(max_length=10)),
                ("style", models.CharField(max_length=255)),
                ("layout", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_layouts",
                        to="pretixbase.event",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
