# Generated by Django 5.2.13 on 2026-05-19 15:39

import django.db.models.deletion
import pretix.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0300_alter_customer_locale_alter_user_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_layouts",
                        to="pretixbase.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name="WalletLayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walletlayout_assignments",
                        to="pretixbase.item",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_assignments",
                        to="wallet.walletlayout",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "layout")},
            },
        ),
        migrations.CreateModel(
            name="WalletPlatformLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("platform", models.CharField(max_length=10)),
                ("style", models.CharField(max_length=255)),
                ("layout", models.JSONField(default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_layouts",
                        to="wallet.walletlayout",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "platform")},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
