# Generated by Django 5.2.13 on 2026-06-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="walletlayoutitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="walletlayout",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="walletlayoutitem",
            name="item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="walletlayout",
                to="pretixbase.item",
            ),
        ),
        migrations.AddConstraint(
            model_name="walletlayout",
            constraint=models.UniqueConstraint(
                models.F("event"),
                condition=models.Q(("default", True)),
                name="one_default_wallet_per_event",
            ),
        ),
    ]
