# Generated by Django 5.2.13 on 2026-08-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_walletlayoutitem_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLayoutFileSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField()),
                ("file", models.FileField(upload_to="")),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_settings",
                        to="wallet.walletplatformlayout",
                    ),
                ),
            ],
        ),
    ]
