# Generated by Django 5.2.17 on 2026-10-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pretixbase",
            "0312_alter_customer_locale_alter_devicelastseen_device_and_more",
        ),
        ("wallet", "0003_walletlayoutfilesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletlayoutitem",
            name="layout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_assignments",
                to="wallet.walletlayout",
            ),
        ),
        migrations.CreateModel(
            name="GoogleWalletInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField()),
                ("identifier", models.CharField()),
                ("data", models.JSONField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("type", "identifier")},
            },
        ),
    ]
