# Generated by Django 3.2.2 on 2021-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixapi', '0005_auto_20191028_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='target_url',
            field=models.URLField(max_length=255),
        ),
    ]
