# Generated by Django 3.2.12 on 2022-09-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0218_checkinlist_addon_match'),
        ('pretixapi', '0007_alter_webhookcall_target_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHookCallRetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('retry_not_before', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(max_length=255)),
                ('logentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_retries', to='pretixbase.logentry')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='pretixapi.webhook')),
            ],
            options={
                'unique_together': {('webhook', 'logentry')},
            },
        ),
    ]
