# Generated by Django 3.2.17 on 2023-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixapi', '0009_auto_20221217_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
