# Generated by Django 4.2.10 on 2024-02-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixapi", "0011_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(default=""),
        ),
    ]
