# Generated by Django 4.2.17 on 2025-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixapi", "0012_oauthapplication_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookcallretry",
            name="retry_not_before",
            field=models.DateTimeField(),
        ),
    ]
