# Generated by Django 4.2.24 on 2025-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixapi", "0013_alter_webhookcallretry_retry_not_before"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="target_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="webhookcall",
            name="target_url",
            field=models.URLField(max_length=1024),
        ),
    ]
