# Generated by Django 4.2.10 on 2024-05-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0267_remove_old_sales_channels"),
        ("ticketoutputpdf", "0008_bigint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketlayoutitem",
            old_name="sales_channel",
            new_name="sales_channel_type",
        ),
        migrations.AlterUniqueTogether(
            name="ticketlayoutitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticketlayoutitem",
            name="sales_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pretixbase.saleschannel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketlayoutitem",
            unique_together={("item", "layout", "sales_channel")},
        ),
    ]
