# Generated by Django 4.2.10 on 2024-05-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0267_remove_old_sales_channels"),
        ("ticketoutputpdf", "0010_sales_channels_migrate_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketlayoutitem",
            name="sales_channel_type",
        ),
        migrations.AlterField(
            model_name="ticketlayoutitem",
            name="sales_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pretixbase.saleschannel",
            ),
        ),
    ]
