# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixdroid', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('Checkin', 'pretixbase_checkin')
    ]

    state_operations = [
        migrations.DeleteModel('Checkin')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
