# Generated by Django 4.2.4 on 2023-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_auto_20190201_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="badgelayout",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
